### PR TITLE
Support for netstandard2.0

### PR DESCRIPTION
**Pull request by SeanFeldman**
I have updated the code to support netstandard 2.0, but the tests are all msmq based, meaning they can't run on netstandard.

@SzymonPobiega could you please help with the testing aspect?

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
I am merging this to a separate branch where I am going to work on the tests

**Comment by SeanFeldman** [comment]
What?! I got it right? Woohoo 😆

**Comment by SzymonPobiega** [comment]
Yeah. Nice job :-)

**Comment by SeanFeldman** [comment]
image

**Pull request merged**
